# Generated by Django 4.2.5 on 2023-10-14 13:36

from django.db import migrations, models
import mod.models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='documents',
            field=models.FileField(default='', upload_to=mod.models.user_directory_path),
        ),
    ]
