# Generated by Django 4.2.5 on 2023-10-15 03:01

from django.db import migrations, models
import django.db.models.deletion
import mod.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('mod', '0003_alter_application_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='documents',
        ),
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('myfiles', models.FileField(default='', upload_to=mod.models.user_directory_path)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.applicant')),
            ],
        ),
    ]
