# Generated by Django 4.2.5 on 2023-10-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0006_alter_userfile_myfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='documents',
            field=models.JSONField(null=True),
        ),
    ]
