# Generated by Django 4.2.5 on 2023-10-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0010_application_fullname_application_postapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='datePrev',
            field=models.DateField(null=True),
        ),
    ]
