# Generated by Django 4.2.5 on 2023-11-06 05:47

from django.db import migrations, models
import mod.models


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0011_application_dateprev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='myfiles',
            field=models.FileField(default='', max_length=1000, upload_to=mod.models.user_directory_path),
        ),
    ]
